# This GitHub Actions workflow file automates the deployment of the Vue frontend.
# It checks out the code, installs dependencies, builds the project, and executes deployment commands (for example, using Netlify CLI).
name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        working-directory: frontend
      - name: Build project
        run: npm run build
        working-directory: frontend
      # Add deployment steps (e.g., Netlify CLI commands) as needed
